#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# fix some Java applications
# wmname LG3D

# workspaces
if [ -x $HOME/bin/dual_monitor ];then
    $HOME/bin/dual_monitor
fi

external_monitor=$(xrandr --query | grep 'HDMI-1' | cut -d ' ' -f2)
if [[ $external_monitor == "connected" ]]; then
	bspc monitor HDMI-1 -d 1 2 3 4 5
	bspc monitor eDP-1 -d 6 7 8 9 0
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi
	
bspc config focus_follows_pointer true

# Window borders (Auto-Generate)
bspc config focused_border_color "#eda539"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#eda539"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
# bspc rule -a firefox state=floating
# bspc rule -a firefox desktop='^2' follow=on

# start resources
sxkf & xrdb -merge $HOME/.Xresources

# autostart
# ============================

xrdb -merge $HOME/.Xresources

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts
~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/cuts/launch.sh &
# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# autostart
flameshot &
~/bin/inverse_scroll &
yandex-disk-indicator
